module Cryptopals.Prelude
    ( catMaybes
    , chunksOf
    , chr
    , findIndex
    , foldl'
    , forM_
    , fromJust
    , isPrint
    , isSpace
    , maximumBy
    , minimumBy
    , on
    , popCount
    , replicateM_
    , toLower
    , toUpper
    , unfoldr
    , xor
    ) where

import           Control.Monad
import           Data.Bits
import           Data.Char
import           Data.Function
import           Data.List
import           Data.List.Split
import           Data.Maybe
